---
- name: install the EPEL packages required for ODCS backend
  package:
    name: "epel-release"
    state: present
  tags:
  - odcs

- name: Use the Fedora infra repo
  copy:
    src: infrastructure.repo
    dest: /etc/yum.repos.d/infrastructure.repo
    mode: 0644
    owner: root
    group: root

- name: install various packages required for ODCS backend
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - fedora-messaging
    - httpd
    - python3-qpid-proton
    - python3-koji-cli-plugins
    - python3-psycopg2
    - python3-celery
    - mock
    - dnf
    - libguestfs-tools-c
  tags:
  - odcs

- name: install the internal packages required for ODCS backend
  package:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - odcs
    - odcs-client
    - python3-odcs-common
    - pungi
    - koji
    - libmodulemd
  tags:
  - odcs

#- name: Make sure odcs-celery-backend isn't running.
#  service:
#    name: odcs-celery-backend
#    state: stopped
#  tags:
#    - odcs
#    - odcs/backend

- name: create odcs-server group
  group:
    name: odcs-server
    gid: 64321
    state: present
 
- name: create odcs-server user
  user:
    name: odcs-server
    uid: 64321
    group: odcs-server
 
- name: ensure ODCS service directories have right ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: odcs-server
    group: odcs-server
    recurse: yes
    follow: no
  with_items:
  - /var/run/odcs-backend
  - /var/log/odcs-backend
  tags:
    - odcs

- name: copy the fedora-messaging.toml.j2 file.
  template:
    src: "fedora-messaging.toml.j2"
    dest: /etc/fedora-messaging/config.toml
    owner: odcs-server
    group: odcs-server
    mode: 0640
  tags:
  - odcs
  
# https://pagure.io/fedora-infrastructure/issue/9450
- name: copy the odcs rabbitmq private queue crt.
  copy:
    src: "{{pkistore}}/rabbitmq-private/centos-odcs-private-queue.crt"
    dest: /etc/odcs/odcs-private-queue.crt
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq private queue key.
  copy:
    src: "{{pkistore}}/rabbitmq-private/centos-odcs-private-queue.key"
    dest: /etc/odcs/odcs-private-queue.key
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq crt.
  copy:
    src: "{{pkistore}}/fedora-messaging/odcs/centos-odcs.crt"
    dest: /etc/odcs/centos-odcs-rabbitmq.crt
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq key.
  copy:
    src: "{{pkistore}}/fedora-messaging/odcs/centos-odcs.key"
    dest: /etc/odcs/centos-odcs-rabbitmq.key
    owner: odcs-server
    mode: 0640
  tags:
  - odcs
 
- name: copy the odcs rabbitmq CA cert.
  copy:
    src: "{{pkistore}}/fedora-messaging/ca.crt"
    dest: /etc/odcs/ca.crt
    owner: odcs-server
    group: apache
    mode: 0640
  tags:
  - odcs

- name: ensure Pungi cache files have right ownership
  file:
    path: "{{ item }}"
    owner: odcs-server
    group: odcs-server
    state: touch
  with_items:
  - /var/tmp/pungi_cache_file.dbm.rw.lock
  - /var/tmp/pungi_cache_file.dbm
  tags:
    - odcs

- name: copy the odcs-celery-backend.service file.
  template:
    src: "etc/systemd/system/odcs-celery-backend.service.j2"
    dest: /etc/systemd/system/odcs-celery-backend.service
    owner: odcs-server
    group: odcs-server
    mode: 0640
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: copy the odcs-backend.conf tmpfiles.d file.
  copy:
    src: "etc/tmpfiles.d/odcs-backend.conf"
    dest: /etc/tmpfiles.d/odcs-backend.conf
    owner: odcs-server
    group: odcs-server
    mode: 0640
  tags:
  - odcs

- name: Run systemd-tmpfiles --create
  command: systemd-tmpfiles --create
  args:
    creates: /var/run/odcs-backend
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: copy the odcs logrotate.d config.
  copy:
    src: "etc/logrotate.d/odcs"
    dest: /etc/logrotate.d/odcs
  tags:
  - odcs

- name: create ODCS_TARGET_DIR
  file:
    path: "{{ odcs_target_dir }}"
    state: directory
    owner: odcs-server
    group: odcs-server
    mode: 0775
    follow: no
  tags:
  - odcs

- name: create ODCS_TARGET_DIR private
  file:
    path: "{{ odcs_target_dir }}/private"
    state: directory
    owner: odcs-server
    group: odcs-server
    mode: 0770
    follow: no
  tags:
  - odcs

- name: enable ODCS backend (odcs-celery-backend)
  systemd:
    name: odcs-celery-backend
    enabled: yes
    daemon_reload: yes
  tags:
  - odcs

- name: generate the ODCS app config
  template:
    src: etc/odcs/config.py.j2
    dest: /etc/odcs/config.py
    owner: odcs-server
    group: odcs-server
    mode: 0440
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: generate the ODCS raw_config_wrapper config
  template:
    src: etc/odcs/raw_config_wrapper.conf.j2
    dest: /etc/odcs/raw_config_wrapper.conf
    owner: odcs-server
    group: odcs-server
    mode: 0444
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: copy the ODCS pungi config template
  copy:
    src: etc/odcs/pungi.conf
    dest: "/etc/odcs/pungi.conf"
    owner: odcs-server
    group: odcs-server
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: copy the ODCS Custom Compose raw_config_wrapper template
  copy:
    src: etc/odcs/custom_compose_raw_config_wrapper.conf
    dest: "/etc/odcs/custom_compose_raw_config_wrapper.conf"
    owner: odcs-server
    group: odcs-server
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: generate the ODCS koji config
  template:
    src: etc/koji.conf.d/odcs.conf.j2
    dest: /etc/koji.conf.d/odcs.conf
    owner: odcs-server
    group: odcs-server
    mode: 0440
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: copy the ODCS keytab (kerberos)
  copy:
    src: "{{ odcs_krb_auth_keytab }}"
    dest: /etc/odcs/odcs.keytab
    owner: odcs-server
    group: odcs-server
    mode: 0440
  when: odcs_koji_authtype  == "kerberos"
  tags:
  - odcs

- name: copy the ODCS user cert (ssl)
  copy:
    src: "{{ pkistore }}/odcs.pem"
    dest: /home/odcs-server/.centos.cert
    owner: odcs-server
    group: odcs-server
    mode: 0600
  when: odcs_koji_authtype  == "ssl"
  tags:
  - odcs

- name: copy the ODCS ca cert (ssl)
  copy:
    src: "{{ pkistore }}/fas_ca_cert-prod.crt"
    dest: /home/odcs-server/.centos-server-ca.cert
    owner: odcs-server
    group: odcs-server
    mode: 0600
  when: odcs_koji_authtype  == "ssl"
  tags:
  - odcs

# This will initialize Alembic if the database is empty, and migrate to the
# latest revision
- name: migrate the database
  command: "{{ item }}"
  with_items:
  - odcs-manager upgradedb
  become: yes
  become_user: odcs-server
  when: odcs_migrate_db
  notify:
  - restart odcs-celery-backend
  tags:
  - odcs

- name: ensure Pungi cache files have right ownership
  file:
    path: "{{ item }}"
    owner: odcs-server
    group: odcs-server
    state: touch
  with_items:
    - /var/tmp/pungi_cache_file.dbm.rw.lock
    - /var/tmp/pungi_cache_file.dbm
  tags:
    - odcs

- name: start ODCS backend (odcs-celery-backend)
  systemd:
    name: odcs-celery-backend
    state: started
  tags:
  - odcs
